name: Actions Ecosystem Action Push Tag
description: Push a Git tag.
author: Actions Ecosystem
inputs:
  tag:
    description: A Git tag name.
    required: true
  message:
    description: A message for the Git tag.
    required: false
  ref:
    description: Commit SHA or ref (tag) to target for the tag.
    required: false
  force:
    description: Whether or not to force push (overwrite) the tag if it already exists. Useful for walking tags.
    type: boolean
    required: false
    default: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: search
  color: yellow
